[book]
title = "Delta Sharing Server"
desciption = "Build and run your own Delta Sharing server implemented in Rust"
authors = ["Tim Dikland"]
language = "en"
multilingual = false
src = "src"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
